### ISSUE TITLE
Steam Deck audio set to wrong device

### ISSUE THREAD

**Issue by J-Lentz** [UAX-Technologies/DeckRC#5]
The default audio device was set incorrectly, causing QGC's sound output to be lost. This was possibly caused by a USB dock which was attached at the time.

**Comment by ConorMcCaffrey** [comment]
Problem has not been occurring on Steamdecks during testing. Have factory restored one deck over five times. A second deck was also unaffected. Marking as a specific to the hardware setup as noted at the time. Can reopen if it occurs again.
